services:
  borg-client:
    image: ghcr.io/desktop31/aio-crossbackup:latest
    container_name: aio-crossbackup_client-ssh
    restart: always
    environment:
      ROLE: client
      ENABLE_WIREGUARD: "false"

      # Backup schedule
      CRON_SCHEDULE: "0 3 * * *"
      # SNAPSHOT_PREFIX: "auto-daily-" # NOTE: use only when backing up zfs snapshots
      # Backup integrity check schedule
      CRON_CHECK_SCHEDULE: "0 1 * * 0"

      # PUSH URL for telling uptime kuma that a backup happened
      KUMA_CLIENT_PUSH_URL: ${KUMA_PUSH_URL}
      # Path to target repository like: "ssh://root@example.com:22/backups"
      # TARGET_REPOSITORY_URL: ${TARGET_REPO_URL}

      # Security
      # Key in this file:
      # SSH_PRIVATE_KEY: |
      #     -----BEGIN OPENSSH PRIVATE KEY-----
      #     67423169...
      #     -----END OPENSSH PRIVATE KEY-----
      # Key in .env:
      SSH_PRIVATE_KEY: ${SSH_KEY_PRIVATE}
    volumes:
      # TODO: specify your paths!
      - ./data_to_backup/:/source_data:ro     
      # Config will be auto-generated here
      - ./config/borgmatic:/etc/borgmatic.d   
      # Preserve keyfile and known_hosts
      - root_data:/root
      - etc_ssh_data:/etc/ssh/

volumes:
  root_data:
  etc_ssh_data:

